### ISSUE TITLE
recursiveTriangle: texture2 uninitialized

### ISSUE THREAD

**Issue by scuzqy** [mkillewald/learnOpenGL#1]
Hi,

I noticed that process starts rendering leaving texture2 uninitialized, adding same initialization should fix it.

**Comment by mkillewald** [comment]
Thanks for pointing this out. It's been a while since I've looked at this code, but I don't think texture2 is being used at all. If I remember right, texture2 was a smiley face in the previous exercise, but was replaced by a shader for the smiley face that follows the mouse pointer in  recursiveTriangle. I'll take a look to be sure and update the code when I get a minute.
